CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author VARCHAR2(255) NOT NULL,
    isbn VARCHAR2(20) NOT NULL UNIQUE,
    publication_year NUMBER CHECK (publication_year >= 1000),
    genre VARCHAR2(100),
    pages NUMBER CHECK (pages > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO books (title, author, isbn, publication_year, genre, pages)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', '9780743273565', 1925, 'Classic Fiction', 180);

INSERT INTO books (title, author, isbn, publication_year, genre, pages)
VALUES ('To Kill a Mockingbird', 'Harper Lee', '9780446310789', 1960, 'Fiction', 281);

INSERT INTO books (title, author, isbn, publication_year, genre, pages)
VALUES ('1984', 'George Orwell', '9780451524935', 1949, 'Dystopian', 328);